spring.application.name=TestApp

server.port=8081

#DB configuration
spring.datasource.url=jdbc:postgresql://postgres-spring.cxceceoeww9b.eu-north-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=root
spring.datasource.password=Postgres_1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


my.variable=global
